batch_presets:
  recommended:
    - model_name: BAAI/bge-base-en-v1.5
      model_for: fe
      task: feature-extraction
      library: transformers
      normalize_embeddings: true

    - model_name: cross-encoder/ms-marco-MiniLM-L-12-v2
      model_for: ranker
      task: sequence-classification
      library: transformers
      optimize: true
